source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftCSS_Example', :exclusive => true do
  pod 'SwiftCSS', :path => '../'
end

target 'SwiftCSS_Tests', :exclusive => true do
  pod 'SwiftCSS', :path => '../'

  
end
